Traceback (most recent call last):
  File "python-scripts/exploration/descr_stats.py", line 83, in <module>
    @plac.annotations(
NameError: name 'plac' is not defined
